task 1-3
js-tasks-ru/jsbasic-20220124_ta1971kor pull request #6
Opened 2022-02-04 12:03 UTC by tatikio

2022-02-04 12:04 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-02-04 13:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-05 11:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-02-05 11:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-02-05 14:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-05 14:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-02-05 14:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-05 16:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-02-06 05:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-06 06:07 UTC, koalex requested changes
Нужно решить `2-module-2-task`

2022-02-06 06:07 UTC, koalex commented on 1-module/3-task/index.js
> +    if (str === '') {
Можно так: `if (!str) return str;`

2022-02-06 17:22 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-02-07 05:21 UTC, koalex approved these changes

2022-02-07 05:22 UTC, merged